In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.2'

In [3]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/gaga/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/gaga/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/gaga/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/gaga/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/gaga/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/gaga/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/gaga/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/gaga/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/gaga/anaconda3/lib']
    define_macr

In [4]:
# 创建长度为 10 的向量
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
# 计算数组的内存大小
z = np.zeros((10,10))
print("%d bytes"%(z.size * z.itemsize))

800 bytes


In [6]:
# 创建一个长度为 10 的向量，其第 5 个值为 1，其他为 0
z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [7]:
# 创建一个包含 10 到 49 所有整数的向量
z = np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
# 反转一个向量
z = z[::-1]
z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [9]:
# 创建一个 3 * 3 的矩阵，包含数字 0 到 8
z = np.arange(0,9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# 转置矩阵
z = np.arange(0,9).reshape(3,3).T
z

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [11]:
# 找出 [1,2,0,0,4,0] 中非 0 的数字位置
z = np.array([1,2,0,0,4,0])
z.nonzero()

(array([0, 1, 4]),)

In [12]:
# 创建 3 * 3 的单位矩阵
z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# 创建 3 * 3 * 3 数组，以随机数字填充
z = np.random.random((3,3,3))
z

array([[[0.08166269, 0.00645052, 0.16892412],
        [0.34237368, 0.80301568, 0.35689862],
        [0.27607307, 0.67026202, 0.23810289]],

       [[0.37462616, 0.53669436, 0.63043956],
        [0.01140489, 0.0645613 , 0.86243191],
        [0.72577367, 0.9977804 , 0.36681719]],

       [[0.28468491, 0.72448104, 0.75610349],
        [0.87934705, 0.03851992, 0.89929562],
        [0.15686674, 0.12360289, 0.28436914]]])

In [14]:
# 创建 10 * 10 的数组，以随机数字填充，并找出其中的最大值和最小值
z = np.random.random((10,10))
z
z.max(),z.min()

(0.9946928704306502, 3.7285662665698105e-05)

In [15]:
# 创建长度为 10 的随机向量，并计算其均值
z = np.random.random((10))
z
z.mean()

0.3366062229795405

In [16]:
# 创建一个二维数组，其边界值为 1，内部值为 0
z = np.ones((5,5))
z[1:-1,1:-1] = 0
z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
# 将现有的数组 (nxn) 用 0 组成的边界包裹
z = np.ones((5,5))
z
m = np.pad(z,(1,1),mode = 'constant',constant_values = 0)
m

# numpy.pad(array,pad_width,mode,***kwargs)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [18]:
# 有 np.nan 参与的算术计算结果都返回 np.nan
0 * np.nan

nan

In [19]:
np.nan == np.nan

False

In [20]:
# 不能比较无穷大和缺失值的大小
np.inf > np.nan

False

In [21]:
np.nan in set([np.nan])

True

In [22]:
0.3 == 3*0.1

False

In [23]:
# allclose 比较浮点数之间的近似相等
np.allclose(0.3, 3*0.1)

True

In [24]:
# 创建一个 5*5 的矩阵，其中 1，2，3，4 刚好在矩阵对角线元素下方
z = np.diag(np.arange(1,5), k = -1)
z


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

`np.diag(array)`
- 如果 array 为**一维数组**，则返回一维数据为对角线元素的矩阵
- 如果 array 为**二维数组**，则返回矩阵的对角线元素

`k`
- 如果 k > 0，则位于对角线**上方**；如果 k < 0，则位于对角线**下方**

In [25]:
# 创建一个 8*8 的矩阵，并由 0，1 标记为国际象棋棋盘的形式
z = np.zeros((8,8))
z
z[1::2,::2] = 1
z[::2,1::2] = 1
z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [26]:
# 现有维度为 6*7*8 的数组，找出其中第 100 个元素的索引(x,y,z)
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [27]:
z = np.arange(6*7*8).reshape(6,7,8)
np.where(z == 99)

(array([1]), array([5]), array([3]))

In [28]:
# 用 tile 函数创建一个 8*8 的棋盘
unit = np.array([[0,1],[1,0]])
z = np.tile(unit,(4,4))
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [29]:
# 标准化一个 5*5 的随机矩阵
z = np.random.random((5,5))
z = (z - z.mean()) / z.std()
z

array([[ 1.15792736,  0.42481781, -1.28309074,  0.4982565 ,  0.0845813 ],
       [-1.1605874 ,  1.87046397, -1.36134073,  0.00341651, -0.05930558],
       [ 1.17917352, -1.45697739, -0.24005767,  0.58252282, -0.80622629],
       [-0.13579566, -1.43693707,  0.23500422, -0.37426513, -0.38951888],
       [ 1.27345031, -0.81635291, -0.72359003,  2.08650535,  0.84792583]])

In [30]:
# 创建一个自定义的包含四个无符号字节 (RGBA) 的 dtype 来描述颜色
color = np.dtype([("r",np.ubype,1),("g",np.ubype,1),("b",np.ubype,1),("a",np.ubype,1)])
color

AttributeError: module 'numpy' has no attribute 'ubype'

In [31]:
# 5*3 的矩阵与 3*2 的矩阵相乘
z = np.dot(np.ones((5,3)),np.ones((3,2)))
z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [32]:
# 也可以使用操作符 @
z = np.ones((5,3)) @ np.ones((3,2))
z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [33]:
# 给定一个一维数组，将值在 3 和 8 之间的数字变为其负数
z = np.arange(10)
z[(z>3)&(z<8)] *= -1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

In [34]:
# 所有数字相加
sum(range(5),-1)

9

In [35]:
# 此处 -1 作为参数，代表多维数组在求和时各个轴求和的顺序
np.sum(range(5),-1)

10

In [36]:
# z 是整数组成的向量，判断下列表达式是否正确
z = np.arange(10)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
# **等算术运算，是元素一一对应进行运算的
z ** z

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [38]:
2<<z>>2
# 本质进行了2次移位运算 等于 (2<<z)>>2

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256])

In [39]:
2 << z 

array([   2,    4,    8,   16,   32,   64,  128,  256,  512, 1024])

In [40]:
part1 = [2 << i for i in range(10)]
part1

[2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]

In [41]:
[i  // 4 for i in part1]

[0, 1, 2, 4, 8, 16, 32, 64, 128, 256]

In [42]:
z < -z
# 等同于 z < (-z)

array([False, False, False, False, False, False, False, False, False,
       False])

In [43]:
# 对复数运算的支持
1j * z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j,
       0.+8.j, 0.+9.j])

In [44]:
z / 1 / 1
# 等同于 (z/1)/1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [45]:
z < z > z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [46]:
l1 = [1,2]
l1 < l1 > l1

False

In [47]:
z < z
z > z

array([False, False, False, False, False, False, False, False, False,
       False])

In [48]:
np.array(0) / np.array(0)
# 0 作为分母提醒

/Users/gaga/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [49]:
np.array(0) // np.array(0)
# 0 作为分母提醒

/Users/gaga/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [50]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

In [51]:
# 舍入浮点数数组，使其尽可能远离 0 
z = np.random.uniform(-10,10,10)
z

array([ 0.05117214,  8.3510088 ,  7.02152607,  8.88525768, -7.94065138,
        8.39159528,  0.14405075,  2.47653319, -0.93623123, -8.0400724 ])

In [52]:
np.copysign(np.ceil(np.abs(z)),z)
# 四舍五入因为正负数不同有不同的结果

array([ 1.,  9.,  8.,  9., -8.,  9.,  1.,  3., -1., -9.])

In [53]:
# 找到两个数组中相同的元素
# 首先考虑内置函数，但不知道的情况下，可以使用 np.lookfor 来找出我们需要的函数
np.lookfor("common values")

TypeError: 'NoneType' object is not iterable

In [ ]:
np.info(np.sum)

In [ ]:
# 如何获取昨天，今天和明天的日期
yesterday = np.datetime64('today','D')- np.timedelta64(1,'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
yesterday, today, tomorrow

In [ ]:
# 如何获取2016年7月全部31天的日期
z = np.arange('2016-07','2016-08', dtype = 'datetime64[D]')
z

In [ ]:
# 如何以替换的方式(in place)计算((A+B)*(-A/2)) -- 不通过复制
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A,B, out = B)
np.divide(A,2, out = A)
np.negative(A, out = A)
np.multiply(A,B,out = A)
A,B

In [ ]:
# 用 5 种方法提取随机数组中的整数部分
z = np.random.uniform(0,10,10)
z

```numpy.random.uniform(low,high,size)```

**[low,high)**

In [ ]:
z - z % 1

In [ ]:
# 向下取整
np.floor(z)

In [ ]:
# 向上取整
np.ceil(z) - 1

In [ ]:
# 转换为 int ，去掉尾数
z.astype(int)

In [ ]:
np.trunc(z)

In [ ]:
# 创建一个 5*5 的矩阵，每行均为 0 到 4
# 1
z = np.zeros((5,5))
z += np.arange(5)
z

In [ ]:
# 2
z = np.tile(np.arange(5),(5,1))
z

In [ ]:
# 现有一个可以生成 10 个整数的生成器函数，利用其建立一个数组
def gen():
    for i in range(10):
        yield i
z = np.fromiter(gen(),dtype = float, count = -1)
z

In [54]:
# 列表解析
z = np.array([i for i in gen()])
z

NameError: name 'gen' is not defined

In [55]:
# 创建一个长度为 10 ，范围从 0 到 1 的向量（不包括 0，1）
z = np.linspace(0,1,11,endpoint=False)[1:]
z

# numpy.linspace(start, stop, step, endPoint = True, restep, dtype)
# endPoint =  True 包含 stop 值

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [56]:
# 创建一个长度为 10 的随机数组并排序
z = np.random.random(10)
z.sort()
z

array([0.0211933 , 0.23881999, 0.43352176, 0.44631306, 0.48735588,
       0.49286785, 0.50755507, 0.586479  , 0.74476418, 0.83024573])

In [57]:
# 对于长度较小的数组，如何更高效的求和(相对于 np.sum)
z = np.arange(19)
np.add.reduce(z)

171

In [58]:
%timeit np.add.reduce(z)

1.09 µs ± 44.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [59]:
%timeit np.sum(z)

2.32 µs ± 11.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [60]:
# 检查两个数组 A、B 是否相等
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# 已知 A,B 的shape 相等
# 存在容错，适用于浮点数的比较
np.allclose(A, B)

False

In [61]:
# 同时检查 shape 与数值
# 要求数值完全相等
np.array_equal(A, B)

False

In [62]:
# 限制数组为不可变数组(read only)
z = np.zeros(10)
z.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [63]:
z.flags.writeable = False
z.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [64]:
z[0]

0.0

In [65]:
# 给定 10*2 矩阵代表平面坐标系中的坐标，将其转化为极坐标系坐标
z = np.random.random((10, 2))
x, y = z[:,0], z[:,1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
r, theta

(array([0.72037893, 1.05027543, 1.01041651, 0.4571613 , 1.25853862,
        1.0191402 , 0.3789241 , 1.01760735, 0.28642266, 1.09696314]),
 array([1.43387332, 0.57033042, 0.17783295, 1.54410655, 0.73721388,
        1.08779371, 0.93177059, 0.79171987, 1.50554416, 1.01316742]))

In [66]:
# 创建一个长度为 10 的随机向量，并将其中最大的数改为 0
z = np.random.random(10)
z

array([0.3389969 , 0.12008312, 0.51627271, 0.69920706, 0.29864068,
       0.86160962, 0.9058072 , 0.76858325, 0.26123164, 0.9384556 ])

In [67]:
z[z.argmax()] = 0
z

array([0.3389969 , 0.12008312, 0.51627271, 0.69920706, 0.29864068,
       0.86160962, 0.9058072 , 0.76858325, 0.26123164, 0.        ])

In [68]:
# 创建一个结构化的数组，其元素为 x 轴， y 轴的坐标，并覆盖 [0,1] * [1,0]
z = np.zeros((5,5),[('x',float),('y',float)])
z = np.meshgrid(np.linspace(0,1,5),
               np.linspace(0,1,5))
z

[array([[0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ]]),
 array([[0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.25, 0.25, 0.25, 0.25, 0.25],
        [0.5 , 0.5 , 0.5 , 0.5 , 0.5 ],
        [0.75, 0.75, 0.75, 0.75, 0.75],
        [1.  , 1.  , 1.  , 1.  , 1.  ]])]

In [69]:
# 给定两个数组 X, Y ，计算其柯西矩阵 C 并求其行列式
x = np.arange(8)
y = x + 0.5
C = np.subtract.outer(x,y)
C

array([[-0.5, -1.5, -2.5, -3.5, -4.5, -5.5, -6.5, -7.5],
       [ 0.5, -0.5, -1.5, -2.5, -3.5, -4.5, -5.5, -6.5],
       [ 1.5,  0.5, -0.5, -1.5, -2.5, -3.5, -4.5, -5.5],
       [ 2.5,  1.5,  0.5, -0.5, -1.5, -2.5, -3.5, -4.5],
       [ 3.5,  2.5,  1.5,  0.5, -0.5, -1.5, -2.5, -3.5],
       [ 4.5,  3.5,  2.5,  1.5,  0.5, -0.5, -1.5, -2.5],
       [ 5.5,  4.5,  3.5,  2.5,  1.5,  0.5, -0.5, -1.5],
       [ 6.5,  5.5,  4.5,  3.5,  2.5,  1.5,  0.5, -0.5]])

In [70]:
np.linalg.det(C)

1.8457040860738383e-92

In [71]:
C_test = x.reshape(8,-1) - y.reshape(1,8)
C_test

array([[-0.5, -1.5, -2.5, -3.5, -4.5, -5.5, -6.5, -7.5],
       [ 0.5, -0.5, -1.5, -2.5, -3.5, -4.5, -5.5, -6.5],
       [ 1.5,  0.5, -0.5, -1.5, -2.5, -3.5, -4.5, -5.5],
       [ 2.5,  1.5,  0.5, -0.5, -1.5, -2.5, -3.5, -4.5],
       [ 3.5,  2.5,  1.5,  0.5, -0.5, -1.5, -2.5, -3.5],
       [ 4.5,  3.5,  2.5,  1.5,  0.5, -0.5, -1.5, -2.5],
       [ 5.5,  4.5,  3.5,  2.5,  1.5,  0.5, -0.5, -1.5],
       [ 6.5,  5.5,  4.5,  3.5,  2.5,  1.5,  0.5, -0.5]])

In [72]:
np.linalg.det(C_test)

1.8457040860738383e-92

In [73]:
np.array_equal(C,C_test)

True

In [74]:
# 打印 Numpy 所有标量乐行（scalar type）可表示的最值
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(f"{dtype}: min = {info.min},max = {info.max}")

for dtype in [np.float16, np.float32, np.float64, np.float128]:
    info = np.finfo(dtype)
    print(f"{dtype}: min = {info.min},max = {info.max}")

<class 'numpy.int8'>: min = -128,max = 127
<class 'numpy.int16'>: min = -32768,max = 32767
<class 'numpy.int32'>: min = -2147483648,max = 2147483647
<class 'numpy.int64'>: min = -9223372036854775808,max = 9223372036854775807
<class 'numpy.float16'>: min = -65504.0,max = 65504.0
<class 'numpy.float32'>: min = -3.4028234663852886e+38,max = 3.4028234663852886e+38
<class 'numpy.float64'>: min = -1.7976931348623157e+308,max = 1.7976931348623157e+308
<class 'numpy.float128'>: min = -inf,max = inf


In [75]:
# 打印数组所有元素（不省略）
with np.printoptions(threshold = np.inf):
    z = np.ones((10,10))
    print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [76]:
# 给定一个数，在数组中找出距离其最近的数
# 给定的数组
z = np.random.uniform(0,1,10)
z

array([0.93864246, 0.74504455, 0.91073504, 0.23722471, 0.49496735,
       0.80987834, 0.95456578, 0.63748325, 0.91084975, 0.69213675])

In [77]:
# 给定的数
x = 0.5
# 定位距离最近数的位置(
index = np.abs(z - x).argmin()
# 找到该数字
z[index]

0.4949673521203938

In [78]:
# 创建一个结构化的数组，其元素为一个坐标 (x,y) 和一个颜色参数 (r,g,b) 
# 一个像素点的表示方式
z = np.zeros(10,[('positon',[('x',float,1),
                             ('y',float,1)]),
                 ('color',[('r',float,1),
                          ('g',float,1),
                          ('b',float,1)])
                ])
z

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('positon', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

In [81]:
# 考虑一个形状为 (10,2) 的随机向量，若其代表二维平面的点，求各点之间的距离
z = np.random.random((10, 2))
x,y = np.atleast_2d(z[:,0],z[:,1])
d = np.sqrt((x - x.T)**2 + (y - y.T)**2)
d

array([[0.        , 0.34283444, 0.83385986, 1.23124119, 0.93911492,
        0.21562401, 0.94891439, 0.82690858, 0.62481196, 1.0619534 ],
       [0.34283444, 0.        , 0.81907218, 1.09497697, 0.8531234 ,
        0.35838114, 0.65774366, 0.64432949, 0.7565186 , 0.96626433],
       [0.83385986, 0.81907218, 0.        , 0.49343425, 0.19410677,
        0.61824475, 0.75690554, 0.40954059, 0.35594984, 0.29039178],
       [1.23124119, 1.09497697, 0.49343425, 0.        , 0.31322182,
        1.02703764, 0.67799979, 0.45564451, 0.84924403, 0.20325817],
       [0.93911492, 0.8531234 , 0.19410677, 0.31322182, 0.        ,
        0.72863621, 0.63277103, 0.29729985, 0.54298656, 0.12302155],
       [0.21562401, 0.35838114, 0.61824475, 1.02703764, 0.72863621,
        0.        , 0.82757935, 0.64681519, 0.43368238, 0.85165766],
       [0.94891439, 0.65774366, 0.75690554, 0.67799979, 0.63277103,
        0.82757935, 0.        , 0.3477681 , 0.96918723, 0.67596378],
       [0.82690858, 0.64432949, 0.4095405

In [82]:
# 也可以使用 scipy 内置函数，效率会更高
import scipy
import scipy.spatial

d = scipy.spatial.distance.cdist(z,z)
d

array([[0.        , 0.34283444, 0.83385986, 1.23124119, 0.93911492,
        0.21562401, 0.94891439, 0.82690858, 0.62481196, 1.0619534 ],
       [0.34283444, 0.        , 0.81907218, 1.09497697, 0.8531234 ,
        0.35838114, 0.65774366, 0.64432949, 0.7565186 , 0.96626433],
       [0.83385986, 0.81907218, 0.        , 0.49343425, 0.19410677,
        0.61824475, 0.75690554, 0.40954059, 0.35594984, 0.29039178],
       [1.23124119, 1.09497697, 0.49343425, 0.        , 0.31322182,
        1.02703764, 0.67799979, 0.45564451, 0.84924403, 0.20325817],
       [0.93911492, 0.8531234 , 0.19410677, 0.31322182, 0.        ,
        0.72863621, 0.63277103, 0.29729985, 0.54298656, 0.12302155],
       [0.21562401, 0.35838114, 0.61824475, 1.02703764, 0.72863621,
        0.        , 0.82757935, 0.64681519, 0.43368238, 0.85165766],
       [0.94891439, 0.65774366, 0.75690554, 0.67799979, 0.63277103,
        0.82757935, 0.        , 0.3477681 , 0.96918723, 0.67596378],
       [0.82690858, 0.64432949, 0.4095405

In [83]:
# 将一个 32 位的浮点数数组，（不适用额外内存）转化为 32 的整数数组
z = np.zeros(10,dtype = np.float32)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [84]:
z = z.astype(np.int32, copy = False)
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [85]:
# 如何读取下面的文件
# 1,2,3,4,5
# 6, , ,7,8
# , ,9,10,11

from io import StringIO
# "假"的文件
s = StringIO("""1,2,3,4,5\n
                6, , ,7,8\n
                 , ,9,10,11\n""")
z = np.genfromtxt(s, delimiter = ",", missing_values = ' ')
z

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])