In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.2'

In [3]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/gaga/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/gaga/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/gaga/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/gaga/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/gaga/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/gaga/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/gaga/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/gaga/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/gaga/anaconda3/lib']
    define_macr

In [4]:
# 创建长度为 10 的向量
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
# 计算数组的内存大小
z = np.zeros((10,10))
print("%d bytes"%(z.size * z.itemsize))

800 bytes


In [6]:
# 创建一个长度为 10 的向量，其第 5 个值为 1，其他为 0
z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [7]:
# 创建一个包含 10 到 49 所有整数的向量
z = np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
# 反转一个向量
z = z[::-1]
z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [9]:
# 创建一个 3 * 3 的矩阵，包含数字 0 到 8
z = np.arange(0,9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# 转置矩阵
z = np.arange(0,9).reshape(3,3).T
z

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [11]:
# 找出 [1,2,0,0,4,0] 中非 0 的数字位置
z = np.array([1,2,0,0,4,0])
z.nonzero()

(array([0, 1, 4]),)

In [12]:
# 创建 3 * 3 的单位矩阵
z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# 创建 3 * 3 * 3 数组，以随机数字填充
z = np.random.random((3,3,3))
z

array([[[0.01476207, 0.294512  , 0.02953534],
        [0.88967006, 0.04820218, 0.07772341],
        [0.06797999, 0.77506959, 0.86639171]],

       [[0.82448251, 0.60219202, 0.15351546],
        [0.95399146, 0.00925017, 0.85143862],
        [0.0447371 , 0.92773375, 0.8351363 ]],

       [[0.12109457, 0.52823648, 0.37312547],
        [0.44255898, 0.88609337, 0.20168079],
        [0.32564341, 0.37872356, 0.72858434]]])

In [14]:
# 创建 10 * 10 的数组，以随机数字填充，并找出其中的最大值和最小值
z = np.random.random((10,10))
z
z.max(),z.min()

(0.9598958824363011, 0.0018021565083362612)

In [15]:
# 创建长度为 10 的随机向量，并计算其均值
z = np.random.random((10))
z
z.mean()

0.43281647495234354

In [16]:
# 创建一个二维数组，其边界值为 1，内部值为 0
z = np.ones((5,5))
z[1:-1,1:-1] = 0
z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
# 将现有的数组 (nxn) 用 0 组成的边界包裹
z = np.ones((5,5))
z
m = np.pad(z,(1,1),mode = 'constant',constant_values = 0)
m

# numpy.pad(array,pad_width,mode,***kwargs)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [21]:
# 有 np.nan 参与的算术计算结果都返回 np.nan
0 * np.nan

nan

In [22]:
np.nan == np.nan

False

In [23]:
# 不能比较无穷大和缺失值的大小
np.inf > np.nan

False

In [24]:
np.nan in set([np.nan])

True

In [25]:
0.3 == 3*0.1

False

In [26]:
# allclose 比较浮点数之间的近似相等
np.allclose(0.3, 3*0.1)

True

In [28]:
# 创建一个 5*5 的矩阵，其中 1，2，3，4 刚好在矩阵对角线元素下方
z = np.diag(np.arange(1,5), k = -1)
z


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

`np.diag(array)`
- 如果 array 为**一维数组**，则返回一维数据为对角线元素的矩阵
- 如果 array 为**二维数组**，则返回矩阵的对角线元素

`k`
- 如果 k > 0，则位于对角线**上方**；如果 k < 0，则位于对角线**下方**

In [30]:
# 创建一个 8*8 的矩阵，并由 0，1 标记为国际象棋棋盘的形式
z = np.zeros((8,8))
z
z[1::2,::2] = 1
z[::2,1::2] = 1
z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [32]:
# 现有维度为 6*7*8 的数组，找出其中第 100 个元素的索引(x,y,z)
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [33]:
z = np.arange(6*7*8).reshape(6,7,8)
np.where(z == 99)

(array([1]), array([5]), array([3]))

In [37]:
# 用 tile 函数创建一个 8*8 的棋盘
unit = np.array([[0,1],[1,0]])
z = np.tile(unit,(4,4))
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [40]:
# 标准化一个 5*5 的随机矩阵
z = np.random.random((5,5))
z = (z - z.mean()) / z.std()
z

array([[ 1.41798414,  0.08128814,  1.36375302, -0.27182123, -1.77858686],
       [ 0.35894304,  0.75178269, -0.52639572,  0.98568942, -0.63531838],
       [-1.17096294,  0.94724633, -1.8326652 ,  0.26670965, -0.73153052],
       [ 0.88296868, -0.19613765,  1.45600593, -1.04591689, -1.01620615],
       [-0.03568071, -0.5273134 ,  0.64338748,  1.60258409, -0.98980695]])

In [41]:
# 创建一个自定义的包含四个无符号字节 (RGBA) 的 dtype 来描述颜色
color = np.dtype([("r",np.ubype,1),("g",np.ubype,1),("b",np.ubype,1),("a",np.ubype,1)])
color

AttributeError: module 'numpy' has no attribute 'ubype'

In [42]:
# 5*3 的矩阵与 3*2 的矩阵相乘
z = np.dot(np.ones((5,3)),np.ones((3,2)))
z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [44]:
# 也可以使用操作符 @
z = np.ones((5,3)) @ np.ones((3,2))
z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [46]:
# 给定一个一维数组，将值在 3 和 8 之间的数字变为其负数
z = np.arange(10)
z[(z>3)&(z<8)] *= -1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

In [47]:
# 所有数字相加
sum(range(5),-1)

9

In [48]:
# 此处 -1 作为参数，代表多维数组在求和时各个轴求和的顺序
np.sum(range(5),-1)

10

In [49]:
# z 是整数组成的向量，判断下列表达式是否正确
z = np.arange(10)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
# **等算术运算，是元素一一对应进行运算的
z ** z

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [51]:
2<<z>>2
# 本质进行了2次移位运算 等于 (2<<z)>>2

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256])

In [52]:
2 << z 

array([   2,    4,    8,   16,   32,   64,  128,  256,  512, 1024])

In [53]:
part1 = [2 << i for i in range(10)]
part1

[2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]

In [54]:
[i  // 4 for i in part1]

[0, 1, 2, 4, 8, 16, 32, 64, 128, 256]

In [55]:
z < -z
# 等同于 z < (-z)

array([False, False, False, False, False, False, False, False, False,
       False])

In [56]:
# 对复数运算的支持
1j * z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j,
       0.+8.j, 0.+9.j])

In [57]:
z / 1 / 1
# 等同于 (z/1)/1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [58]:
z < z > z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [59]:
l1 = [1,2]
l1 < l1 > l1

False

In [60]:
z < z
z > z

array([False, False, False, False, False, False, False, False, False,
       False])

In [61]:
np.array(0) / np.array(0)
# 0 作为分母提醒

/Users/gaga/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [62]:
np.array(0) // np.array(0)
# 0 作为分母提醒

/Users/gaga/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [65]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

In [66]:
# 舍入浮点数数组，使其尽可能远离 0 
z = np.random.uniform(-10,10,10)
z

array([-8.75860648,  4.14157606, -5.99066979, -6.20777647, -1.6280536 ,
        1.47276902, -9.55463751, -8.91002619, -7.03120778, -0.97355002])

In [67]:
np.copysign(np.ceil(np.abs(z)),z)
# 四舍五入因为正负数不同有不同的结果

array([ -9.,   5.,  -6.,  -7.,  -2.,   2., -10.,  -9.,  -8.,  -1.])

In [69]:
# 找到两个数组中相同的元素
# 首先考虑内置函数，但不知道的情况下，可以使用 np.lookfor 来找出我们需要的函数
np.lookfor("common values")

Search results for 'common values'
----------------------------------
numpy.ma.intersect1d
    Returns the unique elements common to both arrays.
numpy.gcd
    Returns the greatest common divisor of ``|x1|`` and ``|x2|``
numpy.lcm
    Returns the lowest common multiple of ``|x1|`` and ``|x2|``
numpy.intersect1d
    Find the intersection of two arrays.
numpy.ma.common_fill_value
    Return the common filling value of two masked arrays, if any.
numpy.add
    Add arguments element-wise.
numpy.less
    Return the truth value of (x1 < x2) element-wise.
numpy.sign
    Returns an element-wise indication of the sign of a number.
numpy.sqrt
    Return the non-negative square-root of an array, element-wise.
numpy.choose
    Construct an array from an index array and a set of arrays to choose from.
numpy.einsum
    einsum(subscripts, *operands, out=None, dtype=None, order='K',
numpy.nditer
    Efficient multi-dimensional iterator object to iterate over arrays.
numpy.greater
    Return the truth v

In [72]:
np.info(np.sum)

 sum(a, axis=None, dtype=None, out=None, keepdims=<no value>,
     initial=<no value>)

Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array and of the accumulator in which the
    elements are summed.  The dtype of `a` is used by default unless `a`
    has an integer dtype of less precision than the default platform
    integer.  In that case, if `a` is signed then the platform integer
    is used while if `a` is unsigned then an unsigned integer of the
    same pr

In [79]:
# 如何获取昨天，今天和明天的日期
yesterday = np.datetime64('today','D')- np.timedelta64(1,'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
yesterday, today, tomorrow

(numpy.datetime64('2019-09-25'),
 numpy.datetime64('2019-09-26'),
 numpy.datetime64('2019-09-27'))

In [82]:
# 如何获取2016年7月全部31天的日期
z = np.arange('2016-07','2016-08', dtype = 'datetime64[D]')
z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [86]:
# 如何以替换的方式(in place)计算((A+B)*(-A/2)) -- 不通过复制
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A,B, out = B)
np.divide(A,2, out = A)
np.negative(A, out = A)
np.multiply(A,B,out = A)
A,B

(array([-1.5, -1.5, -1.5]), array([3., 3., 3.]))

In [87]:
# 用 5 种方法提取随机数组中的整数部分
z = np.random.uniform(0,10,10)
z

array([5.07555068, 0.21193302, 4.33521758, 4.46313056, 2.38819989,
       8.30245732, 7.44764177, 5.86479001, 4.92867853, 4.8735588 ])

```numpy.random.uniform(low,high,size)```

**[low,high)**

In [88]:
z - z % 1

array([5., 0., 4., 4., 2., 8., 7., 5., 4., 4.])

In [89]:
# 向下取整
np.floor(z)

array([5., 0., 4., 4., 2., 8., 7., 5., 4., 4.])

In [90]:
# 向上取整
np.ceil(z) - 1

array([5., 0., 4., 4., 2., 8., 7., 5., 4., 4.])

In [91]:
# 转换为 int ，去掉尾数
z.astype(int)

array([5, 0, 4, 4, 2, 8, 7, 5, 4, 4])

In [92]:
np.trunc(z)

array([5., 0., 4., 4., 2., 8., 7., 5., 4., 4.])

In [93]:
# 创建一个 5*5 的矩阵，每行均为 0 到 4
# 1
z = np.zeros((5,5))
z += np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [94]:
# 2
z = np.tile(np.arange(5),(5,1))
z

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [96]:
# 现有一个可以生成 10 个整数的生成器函数，利用其建立一个数组
def gen():
    for i in range(10):
        yield i
z = np.fromiter(gen(),dtype = float, count = -1)
z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [98]:
# 列表解析
z = np.array([i for i in gen()])
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
# 创建一个长度为 10 ，范围从 0 到 1 的向量（不包括 0，1）
z = np.linspace(0,1,11,endpoint=False)[1:]
z

# numpy.linspace(start, stop, step, endPoint = True, restep, dtype)
# endPoint =  True 包含 stop 值

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [100]:
# 创建一个长度为 10 的随机数组并排序
z = np.random.random(10)
z.sort()
z

array([0.09832853, 0.2667407 , 0.27058423, 0.52230328, 0.56705442,
       0.6050111 , 0.71363667, 0.75354372, 0.88404059, 0.99448158])

In [101]:
# 对于长度较小的数组，如何更高效的求和(相对于 np.sum)
z = np.arange(19)
np.add.reduce(z)

171

In [102]:
%timeit np.add.reduce(z)

1.11 µs ± 25.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [103]:
%timeit np.sum(z)

2.65 µs ± 227 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [104]:
# 检查两个数组 A、B 是否相等
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# 已知 A,B 的shape 相等
# 存在容错，适用于浮点数的比较
np.allclose(A, B)

False

In [105]:
# 同时检查 shape 与数值
# 要求数值完全相等
np.array_equal(A, B)

False

In [106]:
# 限制数组为不可变数组(read only)
z = np.zeros(10)
z.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [107]:
z.flags.writeable = False
z.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [109]:
z[0]

0.0

In [111]:
# 给定 10*2 矩阵代表平面坐标系中的坐标，将其转化为极坐标系坐标
z = np.random.random((10, 2))
x, y = z[:,0], z[:,1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
r, theta

(array([1.19839102, 0.94112373, 0.94915521, 1.1478592 , 1.14398451,
        0.83469229, 1.00697613, 0.49904718, 0.96460445, 0.69099304]),
 array([0.67091643, 0.25481396, 1.02220944, 0.58880436, 0.64979455,
        1.51932591, 1.19459986, 0.25385968, 0.0176515 , 0.20466961]))

In [112]:
# 创建一个长度为 10 的随机向量，并将其中最大的数改为 0
z = np.random.random(10)
z

array([0.15531285, 0.64955775, 0.98165422, 0.69480742, 0.76197389,
       0.42520918, 0.13889344, 0.2161863 , 0.76470027, 0.05460587])

In [113]:
z[z.argmax()] = 0
z

array([0.15531285, 0.64955775, 0.        , 0.69480742, 0.76197389,
       0.42520918, 0.13889344, 0.2161863 , 0.76470027, 0.05460587])

In [116]:
# 创建一个结构化的数组，其元素为 x 轴， y 轴的坐标，并覆盖 [0,1] * [1,0]
z = np.zeros((5,5),[('x',float),('y',float)])
z = np.meshgrid(np.linspace(0,1,5),
               np.linspace(0,1,5))
z

[array([[0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ]]),
 array([[0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.25, 0.25, 0.25, 0.25, 0.25],
        [0.5 , 0.5 , 0.5 , 0.5 , 0.5 ],
        [0.75, 0.75, 0.75, 0.75, 0.75],
        [1.  , 1.  , 1.  , 1.  , 1.  ]])]

In [119]:
# 给定两个数组 X, Y ，计算其柯西矩阵 C 并求其行列式
x = np.arange(8)
y = x + 0.5
C = np.subtract.outer(x,y)
C

array([[-0.5, -1.5, -2.5, -3.5, -4.5, -5.5, -6.5, -7.5],
       [ 0.5, -0.5, -1.5, -2.5, -3.5, -4.5, -5.5, -6.5],
       [ 1.5,  0.5, -0.5, -1.5, -2.5, -3.5, -4.5, -5.5],
       [ 2.5,  1.5,  0.5, -0.5, -1.5, -2.5, -3.5, -4.5],
       [ 3.5,  2.5,  1.5,  0.5, -0.5, -1.5, -2.5, -3.5],
       [ 4.5,  3.5,  2.5,  1.5,  0.5, -0.5, -1.5, -2.5],
       [ 5.5,  4.5,  3.5,  2.5,  1.5,  0.5, -0.5, -1.5],
       [ 6.5,  5.5,  4.5,  3.5,  2.5,  1.5,  0.5, -0.5]])

In [120]:
np.linalg.det(C)

1.8457040860738383e-92

In [121]:
C_test = x.reshape(8,-1) - y.reshape(1,8)
C_test

array([[-0.5, -1.5, -2.5, -3.5, -4.5, -5.5, -6.5, -7.5],
       [ 0.5, -0.5, -1.5, -2.5, -3.5, -4.5, -5.5, -6.5],
       [ 1.5,  0.5, -0.5, -1.5, -2.5, -3.5, -4.5, -5.5],
       [ 2.5,  1.5,  0.5, -0.5, -1.5, -2.5, -3.5, -4.5],
       [ 3.5,  2.5,  1.5,  0.5, -0.5, -1.5, -2.5, -3.5],
       [ 4.5,  3.5,  2.5,  1.5,  0.5, -0.5, -1.5, -2.5],
       [ 5.5,  4.5,  3.5,  2.5,  1.5,  0.5, -0.5, -1.5],
       [ 6.5,  5.5,  4.5,  3.5,  2.5,  1.5,  0.5, -0.5]])

In [123]:
np.linalg.det(C_test)

1.8457040860738383e-92

In [124]:
np.array_equal(C,C_test)

True

In [128]:
# 打印 Numpy 所有标量乐行（scalar type）可表示的最值
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(f"{dtype}: min = {info.min},max = {info.max}")

for dtype in [np.float16, np.float32, np.float64, np.float128]:
    info = np.finfo(dtype)
    print(f"{dtype}: min = {info.min},max = {info.max}")

<class 'numpy.int8'>: min = -128,max = 127
<class 'numpy.int16'>: min = -32768,max = 32767
<class 'numpy.int32'>: min = -2147483648,max = 2147483647
<class 'numpy.int64'>: min = -9223372036854775808,max = 9223372036854775807
<class 'numpy.float16'>: min = -65504.0,max = 65504.0
<class 'numpy.float32'>: min = -3.4028234663852886e+38,max = 3.4028234663852886e+38
<class 'numpy.float64'>: min = -1.7976931348623157e+308,max = 1.7976931348623157e+308
<class 'numpy.float128'>: min = -inf,max = inf


In [129]:
# 打印数组所有元素（不省略）
with np.printoptions(threshold = np.inf):
    z = np.ones((10,10))
    print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [130]:
# 给定一个数，在数组中找出距离其最近的数
# 给定的数组
z = np.random.uniform(0,1,10)
z

array([0.49012299, 0.18069018, 0.63092485, 0.55124203, 0.56708121,
       0.81834498, 0.9389873 , 0.19290141, 0.71284402, 0.6979398 ])

In [131]:
# 给定的数
x = 0.5
# 定位距离最近数的位置(
index = np.abs(z -x).argmin()
# 找到该数字
z[index]

0.4901229891341178